### ISSUE TITLE
[Question] Schedule 생성 시 예외처리

### ISSUE THREAD

**Issue by sihyun615** [BE-Friend-Develop-Team/detour#15]
**❓ Question**
Schedule 생성하다가 발생하는 예외에 대하여 예외 처리를 ScheduleService의 생성 관련 메서드 내에서 try-catch문을 사용하여 해야하는 것이 맞을지 의문이 들어 질문 드립니다!
(try-catch문을 사용한다면 현재 PR에 올라가있는 서비스 내 메서드 내용이 모두 try문에 포함되게 됩니다!)

혹시 다른 좋은 방법이 있다면 알려주시면 감사하겠습니다🙏🏻

**Comment by LeeChangHyeong** [comment]
제 생각엔 try가 너무 길어져 것 같아 가독성이 조금 떨어질 것 같습니다.
상황마다 예외처리를 하는게 저는 더 좋아보입니다!

**Comment by sihyun615** [comment]
> 제 생각엔 try가 너무 길어져 것 같아 가독성이 조금 떨어질 것 같습니다. 상황마다 예외처리를 하는게 저는 더 좋아보입니다!

일정 생성에는 생성 자체에 대한 실패 말고는 딱히 특정 상황에서의 예외처리가 없을 것 같은데
그럼 일단 이 부분은 지금 PR에 있는대로 진행하면 될까요?

**Comment by LeeChangHyeong** [comment]
> > 제 생각엔 try가 너무 길어져 것 같아 가독성이 조금 떨어질 것 같습니다. 상황마다 예외처리를 하는게 저는 더 좋아보입니다!
> 
> 일정 생성에는 생성 자체에 대한 실패 말고는 딱히 특정 상황에서의 예외처리가 없을 것 같은데 그럼 일단 이 부분은 지금 PR에 있는대로 진행하면 될까요?

네! 어짜피 @Transactional이 실패하면 원상복구 시켜주니까 괜찮을 것 같습니다!
